;
(function () {
    require.config({
        baseUrl: "/scripts/",
        skipDataMain: true,
        paths: {
            "jQuery": "../vendor/jquery/dist/jquery",
            "angular": "../vendor/angular/angular",
            "angular-i18n": "../vendor/angular-i18n/angular-locale_zh-cn",
            "angular-route": "../vendor/angular-route/angular-route",
            "angular-cookies": "../vendor/angular-cookies/angular-cookies",
            "angular-animate": "../vendor/angular-animate/angular-animate",
            "angular-resource": "../vendor/angular-resource/angular-resource",
            "angular-sanitize": "../vendor/angular-sanitize/angular-sanitize",
            "angular-base64": "../vendor/angular-base64/angular-base64",
            "angular-growl": "../vendor/angular-growl-v2/build/angular-growl",
            "angular-ui-router": "../vendor/angular-ui-router/release/angular-ui-router",
            "angular-bootstrap": "../vendor/angular-bootstrap/ui-bootstrap-tpls",
            "angular-w5c-validator": "../vendor/angular-w5c-validator/w5cValidator",
            "angular-md5": "../vendor/angular-md5/angular-md5",
            "angular-file-upload": "../vendor/angular-file-upload/dist/angular-file-upload",
            "angular-ui-select2": "../vendor/angular-ui-select2/src/select2",
            "select2": "../vendor/select2/select2",
            "select2-locale-zh-CN": "../vendor/select2/select2_locale_zh-CN",
            "angular-awesome-slider": "../vendor/angular-awesome-slider/dist/angular-awesome-slider",
            "angular-audio": "../vendor/angular-audio/app/angular.audio",
            "angular-busy": "../vendor/angular-busy/dist/angular-busy",
            "angular-touch": "../vendor/angular-touch/angular-touch",
            "v-button": "../vendor/v-button/dist/v-button",
            "datejs": "../vendor/datejs/build/date-zh-CN",
            "amengsms.templates": "dev/templates",
            "qrcode-generator": "../vendor/qrcode-generator/js/qrcode",
            "qrcode_UTF8": "../vendor/qrcode-generator/js/qrcode_UTF8",
            "angular-qrcode": "../vendor/angular-qrcode/angular-qrcode",
            "angular-material": "../vendor/angular-material/angular-material",
            "angular-aria": "../vendor/angular-aria/angular-aria",
            "angular-tags-input": "../vendor/ng-tags-input/ng-tags-input",
            "angulartics": "../vendor/angulartics/src/angulartics",
            "angulartics-google-analytics": "../vendor/angulartics-google-analytics/lib/angulartics-ga",
            "weixin": "../vendor/weixin/jweixin-1.1.0"
        },
        shim: {
            "jQuery": { "exports": "jQuery" },
            "angular": { "exports": "angular", "deps": ["jQuery"] },
            "angular-i18n": { "exports": "angular-i18n", "deps": ["angular"] },
            "angular-route": { "deps": ["angular"], "exports": "angular-route" },
            "angular-cookies": { "deps": ["angular"], "exports": "angular-cookies" },
            "angular-ui-router": { "deps": ["angular"], "exports": "angular-ui-router" },
            "angular-bootstrap": { "deps": ["angular", "angular-i18n"], "exports": "angular-bootstrap" },
            "angular-base64": { "deps": ["angular"], "exports": "angular-base64" },
            "angular-animate": { "deps": ["angular"] },
            "angular-growl": { "deps": ["angular-animate"] },
            "angular-resource": { "deps": ["angular"] },
            "angular-sanitize": { "deps": ["angular"] },
            "angular-w5c-validator": { "deps": ["angular"] },
            "angular-md5": { "deps": ["angular"] },
            "angular-file-upload": { "deps": ["angular"] },
            "angular-aria": { "deps": ["angular"] },
            "angular-ui-select2": { "deps": ["angular", "select2", "select2-locale-zh-CN"] },
            "angular-material": { "deps": ["angular", "angular-animate", "angular-aria"] },
            "angulartics": { "deps": ["angular"] },
            "angulartics-google-analytics": { "deps": ["angular", "angulartics"] },
            "angular-touch": { "deps": ["angular"] },
            "select2": { "deps": ["jQuery"] },
            "select2-locale-zh-CN": { "deps": ["select2"] },
            "angular-audio": { "deps": ["angular"] },
            "angular-busy": { "deps": ["angular"] },
            "angular-awesome-slider": { "deps": ["angular"] },
            "v-button": { "deps": ["angular"] },
            "qrcode_UTF8": { "deps": ["qrcode-generator"] },
            "angular-tags-input": { "deps": ["angular"] },
            "angular-qrcode": { "deps": ["angular","qrcode_UTF8", "qrcode-generator"] }
        },
        waitSeconds: 30,
        urlArgs: "v20161202"
    });
}());